### ISSUE TITLE
How to read ckafka source with oceanus jar job

### ISSUE THREAD

**Issue by wteng** [tencentyun/flink-hello-world#1]
How to read ckafka source with oceanus jar job

**Comment by kylemeow** [comment]
Hi @wteng , you can refer to this [Flink documentation](https://ci.apache.org/projects/flink/flink-docs-release-1.13/zh/docs/connectors/datastream/kafka/) for more details about reading data from Kafka.

AFAIK, CKafka is the same as Kafka from end-users' perspective.
